name: Build Pi Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-image:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup nix environment
        uses: nicknovitski/nix-develop@v1
      - name: Build image
        run: |
          nix build .#cellar

          # Debug: Show result directory structure
          echo "=== Result directory structure ==="
          ls -la result/

          # Debug: Find all .img files
          echo "=== All .img files in result ==="
          find result/ -name "*.img*" -type f 2>/dev/null || echo "No .img files found"

          # Debug: Show what files exist
          echo "=== All files in result ==="
          find result/ -type f 2>/dev/null || echo "No files found"
      - name: Upload Pi image artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-pi4-cellar-image
          path: result/**/cellar-pi.img.zst
          retention-days: 30
          compression-level: 0 # Nix already handles compression
